In [1]:
import numpy as np
import pandas as pd

In [56]:
animal = pd.read_csv("zoo2.csv")

In [57]:
animal.head()

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0      turtle     0         0     1     0         0        1         0   
1   chameleon     0         0     1     0         0        0         0   
2      iguana     0         0     1     0         0        0         1   
3      lizard     0         0     1     0         0        0         1   
4       gecko     0         0     1     0         0        0         0   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        0         1         1         0     0     4     1         1        1   
1        1         1         1         0     0     4     1         1        0   
2        1         1         1         0     0     4     1         1        1   
3        1         1         1         0     0     4     1         0        0   
4        1         1         1         0     0     4     1         1        0   

   class_type  
0           3  
1           3  
2           3  
3           3  
4           3

In [58]:
#variable independen
x = animal.drop(["class_type", "animal_name"], axis = 1)
#variable dependen
y = animal["class_type"]

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 123)

In [61]:
x_test

hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  \
23     0         0     1     0         0        1         0        1   
11     0         0     1     0         0        0         0        1   
26     0         0     1     0         1        0         1        0   
12     0         0     1     0         0        1         0        0   
21     0         0     1     0         0        1         0        1   
10     0         0     1     0         0        1         1        1   
5      0         0     1     0         0        0         1        1   
1      0         0     1     0         0        0         0        1   
6      0         0     1     0         0        0         1        1   

    backbone  breathes  venomous  fins  legs  tail  domestic  catsize  
23         1         1         0     0     4     0         0        0  
11         1         1         0     0     4     1         0        0  
26         0         1         1     0     6     0         0        0  
12         1         0         0     1     0     1         0        0  
21         1         1         0     0     4     0         0        0  
10         1         1         0     0     4     1         0        1  
5          1         1         1     0     0     1         0        1  
1          1         1         0     0     4     1         1        0  
6          1         1         0     0     0     1         0        1

In [62]:
from sklearn.naive_bayes import GaussianNB
modelnb = GaussianNB()

In [63]:
nbtrain = modelnb.fit(x_train, y_train)

nbtrain.class_count_

array([ 7.,  6.,  4., 11.,  6.])

In [64]:
y_pred = nbtrain.predict (x_test)
y_pred

array([5, 3, 6, 4, 5, 3, 3, 3, 3], dtype=int64)

In [65]:
np.array(y_test)

array([5, 3, 6, 4, 5, 3, 3, 3, 3], dtype=int64)

In [66]:
nbtrain.predict_proba(x_test)

array([[0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        2.25167015e-18],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00]])

In [67]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[5, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 1]], dtype=int64)

In [68]:
y_actual = pd.Series([5, 3, 6, 4, 5, 3, 3, 3, 3], name = "actual")
y_pred = pd.Series([5, 3, 6, 4, 5, 3, 3, 3, 3], name = "Prediction")
df_confusion = pd.crosstab(y_actual, y_pred)
df_confusion

Prediction  3  4  5  6
actual                
3           5  0  0  0
4           0  1  0  0
5           0  0  2  0
6           0  0  0  1

In [69]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           3       1.00      1.00      1.00         5
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         2
           6       1.00      1.00      1.00         1

    accuracy                           1.00         9
   macro avg       1.00      1.00      1.00         9
weighted avg       1.00      1.00      1.00         9



In [70]:
! pip install pycm

In [71]:
from pycm import *
y_actuall1 = [0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0]
y_pred1 = [1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0]
print(ConfusionMatrix(y_actuall1, y_pred1))

Predict 0       1       
Actual
0       5       4       

1       5       2       





Overall Statistics : 

95% CI                                                            (0.19442,0.68058)
ACC Macro                                                         0.4375
ARI                                                               -0.05
AUNP                                                              0.42063
AUNU                                                              0.42063
Bennett S                                                         -0.125
CBA                                                               0.39286
CSI                                                               -0.1627
Chi-Squared                                                       0.42328
Chi-Squared DF                                                    1
Conditional Entropy                                               0.9351
Cramer V                                                          0.16265
Cr